#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${1:-/home/kaveh/project/isaacsim_vla_muglift_lab_2026-03-18}"
DOWNLOADS_DIR="$ROOT_DIR/downloads"
ASSETS_DIR="$ROOT_DIR/assets"
RESULTS_DIR="$ROOT_DIR/results"
LOGS_DIR="$ROOT_DIR/logs"
REPO_DIR="$ROOT_DIR/repo"
ISAACSIM_DIR="$ROOT_DIR/isaacsim"

mkdir -p "$DOWNLOADS_DIR" "$ASSETS_DIR" "$RESULTS_DIR" "$LOGS_DIR" "$REPO_DIR" "$ISAACSIM_DIR"

cat <<EOF
ROOT_DIR=$ROOT_DIR
DOWNLOADS_DIR=$DOWNLOADS_DIR
ASSETS_DIR=$ASSETS_DIR
RESULTS_DIR=$RESULTS_DIR
LOGS_DIR=$LOGS_DIR
REPO_DIR=$REPO_DIR
ISAACSIM_DIR=$ISAACSIM_DIR
EOF
