#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${1:-$(cd "$SCRIPT_DIR/.." && pwd)}"
THIRD_PARTY_DIR="$ROOT_DIR/third_party"
DOWNLOADS_DIR="$THIRD_PARTY_DIR/downloads"
ASSETS_DIR="$THIRD_PARTY_DIR/assets"
RESULTS_DIR="$ROOT_DIR/results"
LOGS_DIR="$ROOT_DIR/logs"
REPO_DIR="$ROOT_DIR"
ISAACSIM_DIR="$THIRD_PARTY_DIR/isaacsim"
LIGHTWHEEL_DIR="$THIRD_PARTY_DIR/Lightwheel_Kitchen"

mkdir -p "$DOWNLOADS_DIR" "$ASSETS_DIR" "$RESULTS_DIR" "$LOGS_DIR" "$REPO_DIR" "$ISAACSIM_DIR" "$LIGHTWHEEL_DIR"

cat <<EOF
ROOT_DIR=$ROOT_DIR
THIRD_PARTY_DIR=$THIRD_PARTY_DIR
DOWNLOADS_DIR=$DOWNLOADS_DIR
ASSETS_DIR=$ASSETS_DIR
RESULTS_DIR=$RESULTS_DIR
LOGS_DIR=$LOGS_DIR
REPO_DIR=$REPO_DIR
ISAACSIM_DIR=$ISAACSIM_DIR
LIGHTWHEEL_DIR=$LIGHTWHEEL_DIR
EOF
